services:
  api:
    container_name: express-ts-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8090:8090
    networks:
      - network-backend

networks:
  network-backend:
    driver: bridge
